from __future__ import annotations

import asyncio
import sys
from typing import cast

from pydantic import ValidationError
from telethon import TelegramClient as _TelethonClient
from telethon.sessions import StringSession

from signal_copier.config import Config
from signal_copier.telegram.client import TelegramConfigError


def _is_running_on_railway() -> bool:
    """Return True if this process is running on Railway.app.

    Detected by the presence of either RAILWAY_ENVIRONMENT or
    RAILWAY_PROJECT_ID env vars, which Railway always injects into
    its containers.
    """
    import os

    return bool(os.environ.get("RAILWAY_ENVIRONMENT") or os.environ.get("RAILWAY_PROJECT_ID"))


# Interactive auth has no bound — the user may take minutes to enter
# the SMS code. We use a generous default.
_AUTH_TIMEOUT_SECONDS: int = 300


def _read_creds() -> tuple[int, str, str]:
    """Read API_ID / API_HASH / PHONE from .env via the Config validator.

    Re-uses M2's pydantic validators. On validation failure, prints a
    friendly error to stderr and raises so main() can return 2.
    """
    config = Config()
    return (
        config.telegram_api_id,
        config.telegram_api_hash,
        config.telegram_phone,
    )


async def _do_auth(api_id: int, api_hash: str, phone: str) -> str:
    """Run the Telethon interactive auth flow, return the StringSession string."""
    client = _TelethonClient(StringSession(), api_id, api_hash)
    await client.start(phone=phone)  # interactive: prompts for code + 2FA
    session_str = cast(str, client.session.save())
    await client.disconnect()
    return session_str


def main() -> int:
    """Entry point for `python -m signal_copier.telegram.auth`.

    Reads credentials from .env, runs the Telethon interactive auth
    flow, prints the resulting StringSession to stdout. Exits 0 on
    success, 1 on auth failure, 2 on config error.
    """
    try:
        api_id, api_hash, phone = _read_creds()
    except (ValidationError, ValueError) as exc:
        sys.stderr.write(
            f"❌ Config validation failed; check API_ID / API_HASH / PHONE in .env:\n{exc}\n"
        )
        return 2
    except TelegramConfigError as exc:
        sys.stderr.write(f"❌ {exc}\n")
        return 2

    if api_id == 0 or not api_hash or not phone:
        sys.stderr.write(
            "❌ TELEGRAM_API_ID / TELEGRAM_API_HASH / TELEGRAM_PHONE must be set in .env\n"
            "   Get API_ID and API_HASH from https://my.telegram.org\n"
        )
        return 2

    if _is_running_on_railway():
        sys.stderr.write(
            "❌ Do not run this on Railway. Run `python -m signal_copier.telegram.auth` "
            "locally and paste the printed TELEGRAM_SESSION_STRING into your Railway "
            "Variables.\n"
        )
        return 2

    try:
        session_str = asyncio.run(
            asyncio.wait_for(
                _do_auth(api_id, api_hash, phone),
                timeout=_AUTH_TIMEOUT_SECONDS,
            )
        )
    except TelegramConfigError as exc:
        sys.stderr.write(f"❌ {exc}\n")
        return 2
    except TimeoutError:
        sys.stderr.write(
            f"❌ Auth timed out after {_AUTH_TIMEOUT_SECONDS}s; run again and "
            "respond to the prompts more quickly.\n"
        )
        return 1
    except Exception as exc:
        sys.stderr.write(f"❌ Telegram auth failed: {type(exc).__name__}: {exc}\n")
        return 1

    print("# --- Telegram session ---")
    print("# Generated by `python -m signal_copier.telegram.auth`")
    print(f"TELEGRAM_SESSION_STRING={session_str}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
